
project_id = "pqfawxyxvjocxfhsjdec"

[api]
schemas = ["public", "storage", "graphql_public"]

[auth]
enabled = true

[realtime]
enabled = true

[storage]
enabled = true

[functions.send-push-notification]
verify_jwt = true
