
project_id = "pqfawxyxvjocxfhsjdec"

[functions.generate-response]
verify_jwt = false

[storage]
[storage.buckets]
[storage.buckets.chat_files]
public = true
file_size_limit = "10MB"
allowed_mime_types = ["image/*"]

