
project_id = "pqfawxyxvjocxfhsjdec"

[functions.create-plaid-link-token]
verify_jwt = true

[functions.generate-response]
verify_jwt = false

[functions.simulate-plaid-webhook]
verify_jwt = false

[functions.transaction-webhook]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = true

[storage]
[storage.buckets]
[storage.buckets.transaction_attachments]
public = true
file_size_limit = "10MB"
allowed_mime_types = ["image/*"]
