// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqfawxyxvjocxfhsjdec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxZmF3eHl4dmpvY3hmaHNqZGVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyODkzODcsImV4cCI6MjA1NDg2NTM4N30.VemMqbAyx6OWqIjpbqcEK-9VK8OLs013XZlsRbvwHnU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);